frameworkVersion: '2'
service: cs

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:GetBucketLocation
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: arn:aws:s3:::buckety-boo-bucket/*
            
resources: 
  Resources:
    TxtBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: buckety-boo-bucket

functions:
  craigslist:
    handler: main.craigslist_scraper
    events:
      - http:
          method: get
          path: craigslist_scraper

plugins:
  - serverless-python-requirements
